package builder

//Config contains all the data about the range of values that different parts of a graph can be when autogenerated.
//This allows for testing different sizes of graphs without having to adjust hardcoded values
type Config struct {
	BaseNumNodes     int     `json:"base_num_nodes"`
	ExtraNumNodes    int     `json:"extra_num_nodes"`
	ChanceCrossRoads float64 `json:"chance_cross_roads"`
	BaseNodeRate     int     `json:"base_node_rate"`
	ExtraNodeRate    int     `json:"extra_node_rate"`
	BaseNodeDiff     int     `json:"base_node_diff"`
	ExtraNodeDiff    int     `json:"extra_node_diff"`
	BaseNumEdges     int     `json:"base_num_edges"`
	ExtraNumEdges    int     `json:"extra_num_edges"`
	BaseEdgeWeight   int     `json:"base_edge_weight"`
	ExtraEdgeWeight  int     `json:"extra_edge_weight"`
}
